USE [RefactorResume];

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
          WHERE TABLE_NAME = 'contacts' AND COLUMN_NAME = 'ImageUrl')

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
          WHERE TABLE_NAME = 'contacts' AND COLUMN_NAME = 'Note')   

BEGIN
    ALTER TABLE contacts
    DROP COLUMN Note, ImageUrl;
END

ALTER TABLE contacts
ADD ImageUrl NVARCHAR (2048) NULL;

ALTER TABLE contacts
ADD Note NVARCHAR (500) NULL;